---
title: Receiver
---
flowchart TB
    A(["SETUP"]) --> B("setup serial port")
    B --> G[["setup LORA hardware"]]
    G --> C("Setup LORA buffer")
    C --> E[["Setup Core 1 - processTask"]]
    E --> F[["Setup Core 0 - LORATask"]]
    F --> D{"LORA buffer setup ?"}
    D -- no --> H("buffer setup failed")
    H --> H
    D -- yes --> J("Print Receiver Version")
    J --> 8a("Print OTA Partition data")
    8a --> L("Setup hardware i/o")
    L --> 10a{"DebugMode Selected?"}
    10a -- no --> aa(("aa"))
    10a -- yes--> 10b("Print message 'Debug Mode'")
    10b --> 10c("Point bot to Debug Mode BOT")
    10c -->aa("Setup One-Wire") 
    aa-->10d{Look for WiFi} 
    10d-- no -->aa
    10d--yes-->23a("Setup WiFiconnection")


          
