; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
board_build.partitions = partitions.csv
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
upload_port = /dev/ttyUSB0
lib_deps = 
	Heltec_ESP32_LoRa_v3
	RadioLib
	olikraus/U8g2@^2.35.19
	tzapu/WiFiManager@^2.0.17
	adafruit/Adafruit DS248x@^1.2.0
	adafruit/Adafruit BusIO@^1.17.4
	mobizt/ESP Mail Client@^3.4.24
	arduino-libraries/NTPClient@^3.2.1
	witnessmenow/UniversalTelegramBot@^1.3.0
