flowchart TD

    A([Start sendEmailAlert])

    A --> B{WiFi Connected?}

    B -->|No| C[Print 'Cannot send email - WiFi not connected']
    C --> D([Return])

    B -->|Yes| E[Initialize recipient loop i = 0]

    E --> F{i < 6 recipients?}

    F -->|No| D

    F -->|Yes| G{Valid Email?<br/>Length > 5 AND contains @}

    G -->|No| H[Increment i]
    H --> F

    G -->|Yes| I[Print Added Email Recipient]

    I --> J[Enable MailClient Network Reconnect]

    J --> K[Enable SMTP Debug Level 1]

    K --> L[Set SMTP Callback Function]

    L --> M[Create ESP_Mail_Session]

    M --> N[Configure SMTP Server<br/>Host, Port]

    N --> O[Configure Sender Login<br/>Email, Password]

    O --> P[Configure NTP Time Settings]

    P --> Q[Create SMTP Message]

    Q --> R[Set Sender Name and Email]

    R --> S[Set Email Subject]

    S --> T[Add Recipient]

    T --> U[Build HTML Email Content]

    U --> V[Set HTML Content<br/>Charset and Encoding]

    V --> W[Set Message Priority]

    W --> X[Set Notification Options]

    X --> Y{SMTP Connect Successful?}

    Y -->|No| D

    Y -->|Yes| Z[Send Email]

    Z --> AA{Email Sent Successfully?}

    AA -->|No| AB[Print SMTP Error Reason]

    AA -->|Yes| AC[Email Sent Successfully]

    AB --> AD[Increment i]
    AC --> AD

    AD --> F
