flowchart TD
    A([Start Help])
    A --> B[Print to Telegram  - Commands: ]
 B--> C[Print to Telegram - /status    - Status of Receiver/Sender]
 C --> D[Print to Telegram - /rom       - ROM assignments]
 D --> E[Print to Telegram -  /help      - Available commands]
