flowchart TD

    A([Start Super Help])

    A --> B[Print Commands: <br>
  /status    - Status of Receiver/Sender<br>
 /rom       - ROM assignments<br>
 /debug-on  - Sender Debug mode on<br>
 /debug-off - Sender Debug mode off<br>
 /WDT-on    - Watchdog mode on<br>
  /WDT-off   - Watchdog mode off<br>
  /ota       - Receiver OTA information<br>
  /_UPDATE   - Update Receiver firmware<br>
  /_RESET    - Receiver Reset<br>
  /help      - Available commands<br>
  /superhelp - SuperUser commands<br>]