flowchart TD

    A([Telegram Command Received])

    A --> B{Command?}

    %% OTA
    B -->|/ota| C[Gather OTA Information]
    C --> D[Build Response String]
    D --> E[Send Telegram Message]

    %% Debug ON
    B -->|/debug-on| F[Set debug_flag_from_receiver = true]
    F --> G[Send 'Debug mode turned ON']

    %% Debug OFF
    B -->|/debug-off| H[Set debug_flag_from_receiver = false]
    H --> I[Send 'Debug mode turned OFF']

    %% RESET
    B -->|/_RESET| J[Set telegramResetFlag = true]
    J --> K[Send 'Receiver is resetting...']

    %% UPDATE
    B -->|/_UPDATE| L[Send 'Updating Receiver firmware...']
    L --> M[Set telegramUpdateFlag = true]

    %% ROM
    B -->|/rom| N[Initialize Empty String]
    N --> O{{Loop Through 14 ROM Entries}}
    O --> P[Append Depth Label]
    P --> Q{ROM Assigned?}
    Q -->|Yes| R[Append ROM Address]
    Q -->|No| S[Append 'Not Assigned']
    R --> T{More Entries?}
    S --> T
    T -->|Yes| O
    T -->|No| U[Send Telegram Message]

    %% WDT ON
    B -->|/WDT-on| V[Set watchdogEnableFlag = true]
    V --> W[Save Operator Variables]
    W --> X[Send 'Watchdog ON']

    %% WDT OFF
    B -->|/WDT-off| Y[Set watchdogEnableFlag = false]
    Y --> Z[Save Operator Variables]
    Z --> AA[Send 'Watchdog OFF']
